#!/bin/bash
# Generates Shared/Generated/BuildInfo.swift from the current git state.
# Wired as a PRE-BUILD "Run Script" phase so every build stamps the binary
# with the commit it was actually compiled from. Because the output lives in
# Shared/, the host app and both system extensions all compile the same value,
# which is what lets you spot a stale, macOS-cached extension at runtime.
set -euo pipefail

# Xcode build phases inherit a stripped PATH; make sure git is findable.
export PATH="/usr/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_DIR/Shared/Generated"
OUT_FILE="$OUT_DIR/BuildInfo.swift"

cd "$REPO_DIR"

if git rev-parse --git-dir >/dev/null 2>&1; then
    COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
        DIRTY="true"
    else
        DIRTY="false"
    fi
    BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
else
    # Source archive with no .git (e.g. CI from tarball) — degrade gracefully.
    COMMIT="unknown"
    DIRTY="false"
    BRANCH="unknown"
fi
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$OUT_DIR"

NEW_CONTENTS="$(cat <<EOF
// Generated by tools/gen-buildinfo.sh — DO NOT EDIT.
// Regenerated on every build from the git working tree.
import Foundation

enum BuildInfo {
    /// Short git commit the binary was compiled from.
    static let commit = "$COMMIT"
    /// True if the working tree had uncommitted changes at build time.
    static let dirty = $DIRTY
    /// Branch checked out at build time.
    static let branch = "$BRANCH"
    /// UTC timestamp of the build.
    static let builtAt = "$BUILT_AT"

    /// Human-readable stamp, e.g. "555c587+dirty".
    static var stamp: String { dirty ? "\(commit)+dirty" : commit }
}
EOF
)"

# Only rewrite when content changes, so we don't force a needless recompile
# (and re-stamp the timestamp) on every incremental build.
if [ ! -f "$OUT_FILE" ] || [ "$(cat "$OUT_FILE")" != "$NEW_CONTENTS" ]; then
    printf '%s\n' "$NEW_CONTENTS" > "$OUT_FILE"
fi
